port=${1:-12222}
server="localhost"
origin="Origin: http://$server:$port/"
echo "RESURS: KORISNICI"
echo "GET"
curl -H "$origin" -X GET "http://$server:$port/api/korisnici/"
echo ""
echo "POST"
curl -H "$origin" -X POST "http://$server:$port/api/korisnici/" -H 'Content-Type: application/json' -d '{"ime":"Test", "prezime":"Test", "lozinka":"123456", "email":"test3@foi.unizg.hr", "korime":"test"}'
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://$server:$port/api/korisnici/"
echo ""
echo "PUT"
curl -H "$origin" -X PUT "http://$server:$port/api/korisnici/"
echo ""
echo ""
echo "RESURS: KORISNICI/matnovak"
echo "GET"
curl -H "$origin" -X GET "http://$server:$port/api/korisnici/matnovak"
echo ""
echo "GET prijava tocna"
curl -H "$origin" -X POST "http://$server:$port/api/korisnici/matnovak/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"123456"}'
echo ""
echo "GET prijava kriva"
curl -H "$origin" -X POST "http://$server:$port/api/korisnici/matnovak/prijava" -H 'Content-Type: application/json' -d '{"lozinka":"12345"}'
echo ""
echo ""
echo "RESURS: KORISNICI/test"
echo "PUT"
echo "Staro"
curl -H "$origin" -X GET "http://$server:$port/api/korisnici/test"
echo ""
echo "Azuriram"
curl -H "$origin" -X PUT "http://$server:$port/api/korisnici/test" -H 'Content-Type: application/json' -d '{"ime":"Test3", "prezime":"Test", "lozinka":"123456", "email":"test2@foi.unizg.hr"}'
echo ""
echo "Novo"
curl -H "$origin" -X GET "http://$server:$port/api/korisnici/test"
echo ""
echo "DELETE"
curl -H "$origin" -X DELETE "http://$server:$port/api/korisnici/test"
echo ""
echo "POST"
curl -H "$origin" -X POST "http://$server:$port/api/korisnici/test"
echo ""
